name: 'Verify Semantic Changelog Update'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: GetStream/verify-semantic-changelog-update@test/test
        with:
          scopes: '{"ui": "src", "llc": "src", "core": "src", "repo": "."}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
