name: 'Verify Semantic Changelog Update'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  conventional_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  main:
    needs: conventional_pr_title
    runs-on: ubuntu-latest
    steps:
      - uses: GetStream/verify-semantic-changelog-update@main
        with:
          scopes: |
            {
              "ui": "src",
              "repo": "."
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
